### ISSUE TITLE
There is no options page to change the value of trottoInstanceUrl

### ISSUE THREAD

**Issue by Ferdy89** [trotto/browser-extension#1]
Hi! I love Trotto, thanks for making it open source!

I noticed the extension supports an arbitrary domain other than trot.to, but in order to edit it one must go to the Chrome DevTools to edit the value of `localStorage.trottoInstanceUrl`.

I believe it'd be nice to have an options page for the extension to be able to edit that.

I would be happy to give that a shot :)

**Comment by itsojon** [comment]
Hey @Ferdy89! That would be excellent, as a lower-friction alternative to loading the unpacked extension or deploying your own edition. Go for it!

**Comment by itsojon** [comment]
@Ferdy89 in case you're still interested in making this change, I updated the repo yesterday with significant improvements to the README and a proper build/dev system. The latest commit also consolidates the code used to get the current go links instance to [`src/config.js`](https://github.com/trotto/browser-extension/blob/9ba4a235872dbbca3b3fb13b3dd7440e19958270/src/config.js).

**Comment by jflinter** [comment]
@itsojon Hello! I find myself wanting this feature, and would be willing to build it. I just want to check on the status of the extension etc before spending time on an implementation. Would you accept a PR here, and once accepted would that PR make its way into production reasonably quickly?

**Comment by itsojon** [comment]
thank you, @jflinter! yes, we'd accept a PR here and release to production within a few days of the merge. just share how you have in mind to implement this first so we can be sure we're on the same page before you spend time implementing.

**Comment by jflinter** [comment]
Great!

I'd likely implement a settings page with a single option per https://developer.chrome.com/docs/extensions/mv3/options/ . Specifically I would make an embedded form per https://developer.chrome.com/docs/extensions/mv3/options/#embedded_options .

Both Chrome and Firefox recommend that you use `storage` instead of `localStorage` for storing settings; I wouldn't change that as part of this work, however.

How does that sound @itsojon, anything I'm missing?

**Comment by itsojon** [comment]
sounds like a plan, @jflinter! my only additional request would be to provide an easy way to reset to the default instance.

also note that Trotto is still on manifest v2, but on first glance it doesn't seem like anything changed from v2 to v3 as far as options go.

**Comment by jflinter** [comment]
Cool - mind having a look @itsojon?
